vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: '%app.path.image%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.image%'
